FROM node:20-alpine

# Instalar OpenSSL para conexiones SSL/TLS a MongoDB
RUN apk add --no-cache openssl

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV PORT=5000
EXPOSE 5000
CMD ["npm", "start"]
